services:
  ctr-utils:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${RELEASE}
    container_name: ${SRV_NAME}
    volumes:
      - ${VOL_SCRIPTS}
      - ${VOL_CRON}
      - ${VOL_DOCKE_SOCK}
      - ${VOL_DOCKER_BIN}
      - ${VOL_LOCALTIME}
    environment:
      # SMB config
      SMB_SHARE: ${SMB_SHARE}
      SMB_REMOTE_FILE: ${SMB_REMOTE_FILE}
      SMB_USER: ${SMB_USER}
      SMB_PASS: ${SMB_PASS}
    networks:
      network-share:
        ipv4_address: ${CONTAINER_IP}
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/scripts/entrypoint.sh"]
networks:
  network-share:
    external: true
    ipam:
      config:
        - subnet: ${SUBNET}
