name: Hadolint

# =========================================================
# WORKFLOW: Hadolint
# ---------------------------------------------------------
# Finalidade:
# Validar o Dockerfile do projeto com Hadolint.
#
# O Hadolint verifica boas práticas, padronização e problemas
# comuns de Dockerfile.
#
# Estratégia atual:
# - workflow bloqueante
# - se o Dockerfile tiver achados relevantes, o job falha
#
# Gatilhos:
# - push na branch main
# - pull request
# - execução manual
# =========================================================

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #workflow_dispatch:

permissions:
  contents: read

jobs:
  hadolint:
    name: Hadolint - Validar Dockerfile
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório no runner
      - name: Checkout do repositório
        uses: actions/checkout@v5

      # Executa o Hadolint no Dockerfile da raiz do projeto
      - name: Rodar Hadolint no Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile